version: '3'

services:

  node:
    build:
      context: node
    command: "node index.js"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    container_name: app_node
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - rndnet
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db_mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db_teste
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - rndnet

networks:
   rndnet:
      driver: bridge
